import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';

//Providers
import '../providers/video.dart';

class VideosProvider with ChangeNotifier {
  List<Video> _videos = [];

  List<Video> get video {
    return [..._videos];
  }

  void loadVideos() {
    _videos = [
      Video(
        id: 'x606y4QWrxo1',
        author: 'currentUser',
        title: 'Ad Astra',
        trailerURL: 'assets/trailers/adastra.mp4',
        imageUrl:
            'https://m.media-amazon.com/images/I/813iyI20fKL._AC_SY550_.jpg',
        bannerUrl:
            'https://w0.peakpx.com/wallpaper/227/724/HD-wallpaper-ad-astra-2019-movie.jpg',
        age: '14',
        release: '2019',
        rate: '8.5',
        time: '2h 4m',
        genre: 'Adventure',
        castImages: [
          'https://images.mubicdn.net/images/cast_member/2552/cache-207-1524922850/image-w856.jpg',
          'https://m.media-amazon.com/images/M/MV5BMTkyNjc4MDc0OV5BMl5BanBnXkFtZTcwOTc5OTUwOQ@@._V1_.jpg',
          'https://br.web.img3.acsta.net/r_1280_720/medias/nmedia/18/81/99/55/20201425.jpg',
          'https://br.web.img3.acsta.net/pictures/20/01/09/01/28/3536010.jpg',
          'https://fr.web.img6.acsta.net/pictures/19/08/30/10/22/5000319.jpg',
          'https://br.web.img2.acsta.net/pictures/19/03/08/22/10/0741995.jpg',
          'https://br.web.img2.acsta.net/pictures/19/03/08/22/10/0741995.jpg ',
          'https://br.web.img2.acsta.net/pictures/17/04/07/12/28/474620.jpg',
          'https://images.mubicdn.net/images/cast_member/116403/cache-243949-1528785046/image-w856.jpg',
          'https://flxt.tmsimg.com/assets/68350_v9_bb.jpg',
          'https://flxt.tmsimg.com/assets/71707_v9_bb.jpg',
          'https://static.wikia.nocookie.net/howtogetawaywithmurderabc/images/d/dd/Elisa_Perry.png',
          'https://images.mubicdn.net/images/cast_member/39551/cache-447934-1561569068/image-w856.jpg',
          'https://images.mubicdn.net/images/cast_member/29994/cache-568341-1595262840/image-w856.jpg',
          'https://images.mubicdn.net/images/cast_member/37371/cache-244674-1502088093/image-w856.jpg',
        ],
        castNames: [
          'Brad Pitt',
          'Tommy Lee Jones',
          'Donald Sutherland',
          'Ruth Negga',
          'Liv Tyler',
          'Kayla Adams',
          'Natasha Lyonne',
          'Kimberly Elise',
          'Greg Bryk',
          'John Ortiz',
          'Loren Dean',
          'Elisa Perry',
          'Ravi Kapoor',
          'Donnie Keshawarz',
          'John Finn',
        ],
        storyline: [
          'Astronaut Roy McBride undertakes a mission across an unforgiving solar system to uncover the truth about his missing father and his doomed expedition that now, 30 years later, threatens the universe.'
        ],
      ),
      Video(
        author: 'currentUser',
        id: 'vrPk6LB9bjo2',
        title: 'Blade Runner 2049',
        trailerURL: 'assets/trailers/bladerunne2049.mp4',
        imageUrl:
            'https://images-na.ssl-images-amazon.com/images/M/MV5BNzA1Njg4NzYxOV5BMl5BanBnXkFtZTgwODk5NjU3MzI@._V1_.jpg',
        bannerUrl:
            'https://www.hdwallpapers.in/download/ryan_gosling_blade_runner_2049_hd-1080x1920.jpg',
        age: '14',
        release: '2019',
        rate: '8.5',
        time: '2h 4m',
        genre: 'Action',
        castImages: [
          'https://media.fstatic.com/lhwC16sJLL8yuSeFFX9GCMKhi-k=/full-fit-in/290x478/filters:format(webp)/media/artists/avatar/2016/12/ryan-gosling_a106376_pXORbNR.jpg',
          'https://static.wikia.nocookie.net/ptstarwars/images/d/d4/Harrison.jpg/revision/latest?cb=20061120214705',
          'https://cdna.artstation.com/p/assets/images/images/045/088/954/large/xie-boli-8.jpg?1641899042',
          'https://br.web.img2.acsta.net/pictures/19/10/30/17/02/0678166.jpg',
          'https://media.fstatic.com/cejoFyGSpmlb24YIGokDOArqS5c=/full-fit-in/290x478/filters:format(webp)/media/artists/avatar/2018/05/mackenzie-davis_a280208.jpg',
          'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Jared_Leto_by_Gage_Skidmore.jpg/800px-Jared_Leto_by_Gage_Skidmore.jpg',
          'https://images.mubicdn.net/images/cast_member/22303/cache-2934-1543703714/image-w856.jpg',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSoMi020Rj8HJiMdssldLTB3qTwwsPOg4aAlA&usqp=CAU',
          'https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Carla_Juri%2C_Laura_Birn_%282%29_%28cropped_-_Juri%29.jpg/250px-Carla_Juri%2C_Laura_Birn_%282%29_%28cropped_-_Juri%29.jpg',
        ],
        castNames: [
          'Ryan Gosling',
          'Harrison Ford',
          'Ana de Armas',
          'Sylvia Hoeks',
          'Mackenzie Davis',
          'Mackenzie Davis',
          'Robin Wright',
          'Dave Bautista',
          'Carla Juri',
        ],
        storyline: [
          "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years."
        ],
      ),
      Video(
        id: 'ilX5hnH8XoI3',
        author: 'currentUser',
        title: 'Ex Machina',
        trailerURL: 'assets/trailers/exmachina.mp4',
        imageUrl:
            'https://m.media-amazon.com/images/I/61NXaDOlYpL._AC_SX679_.jpg',
        bannerUrl: 'https://wallpapercave.com/wp/wp2236201.jpg',
        age: '14',
        release: '2019',
        rate: '8.5',
        time: '2h 4m',
        genre: 'SciFi',
        castImages: [],
        castNames: [
          'Brad Pitt',
          'Tommy Lee Jones',
          'Donald Sutherland',
          'Ruth Negga',
          'Liv Tyler',
          'Kayla Adams',
          'Natasha Lyonne',
          'Kimberly Elise',
          'Greg Bryk',
        ],
        storyline: [
          'A young programmer is selected to participate in a ground-breaking experiment in synthetic intelligence by evaluating the human qualities of a highly advanced humanoid A.I.'
        ],
      ),
      Video(
        id: 'ilX5hnH8XoI4',
        author: 'currentUser',
        title: 'Avatar',
        trailerURL: 'assets/trailers/avatar.mp4',
        imageUrl:
            'https://upload.wikimedia.org/wikipedia/en/thumb/d/d6/Avatar_%282009_film%29_poster.jpg/220px-Avatar_%282009_film%29_poster.jpg',
        bannerUrl: 'https://wallpaperaccess.com/full/1816364.jpg',
        age: '14',
        release: '2019',
        rate: '8.5',
        time: '2h 4m',
        genre: 'Action',
        castImages: [
          'https://br.web.img3.acsta.net/c_310_420/pictures/19/10/17/01/24/5480352.jpg',
          'https://www.pearlanddean.com/wp-content/uploads/2022/12/uuid4f50968a-5eb4-4ebc-91fb-dcfbf1a90673groupId10139t1670421794211.jpg',
          'https://media.fstatic.com/aQWQneY5DIRfD4unUrjZFc062N8=/210x312/smart/filters:format(webp)/media/artists/avatar/2021/10/sigourney-weaver_a72.jpg',
          'https://br.web.img3.acsta.net/c_310_420/pictures/18/11/22/23/44/2914666.jpg',
          'https://static.wikia.nocookie.net/forever1085/images/8/81/Joel_David_Moore.jpg/revision/latest?cb=20141207012430',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZ8qmWWHo_RhaFCitZpnhk0n5mdObBPRDlv2wQbsEjbijkvSSp8vJyxkp1V34O-Ja1_Rg&usqp=CAU',
          'https://static.wikia.nocookie.net/jamescameronsavatar/images/0/06/Giovanni_Ribisi_Avatar_2.jpg/revision/latest?cb=20221215034032',
          'https://media.fstatic.com/ZVrFMm62AEJFvzVQqXG_XWXttZ4=/210x312/smart/filters:format(webp)/media/artists/avatar/2022/12/stephen-lang-i_a6152.jpg',
          'https://musicimage.xboxlive.com/catalog/video.contributor.5bf26400-0200-11db-89ca-0019b92a3933/image?locale=en-nz&target=circle',
        ],
        castNames: [
          'Zoë Saldaña',
          'Sam Worthington',
          'Sigourney Weaver',
          'Michelle Rodriguez',
          'Joel Moore',
          'Laz Alonso',
          'Giovanni Ribisi',
          'Stephen Lang',
          'CCH Pounder',
        ],
        storyline: [
          'A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.'
        ],
      ),
      Video(
        id: 'ilX5hnH8XoI5',
        author: 'currentUser',
        title: 'Interstellar',
        trailerURL: 'assets/trailers/interstellar.mp4',
        imageUrl:
            'https://m.media-amazon.com/images/I/A1JVqNMI7UL._AC_SL1500_.jpg',
        bannerUrl:
            'https://media.idownloadblog.com/wp-content/uploads/2014/12/interstellar-sea-film-space-art-34-iphone6-plus-wallpaper.jpg',
        age: '14',
        release: '2019',
        rate: '8.5',
        time: '2h 4m',
        genre: 'SciFi',
        castImages: [],
        castNames: [
          'Brad Pitt',
          'Tommy Lee Jones',
          'Donald Sutherland',
          'Ruth Negga',
          'Liv Tyler',
          'Kayla Adams',
          'Natasha Lyonne',
          'Kimberly Elise',
          'Greg Bryk',
        ],
        storyline: [
          "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival."
        ],
      ),
      Video(
        id: 'ilX5hnH8XoI6',
        author: 'currentUser',
        title: 'Dune',
        trailerURL: 'assets/trailers/dune.mp4',
        imageUrl:
            'https://upload.wikimedia.org/wikipedia/pt/thumb/c/c0/Dune_2020.jpeg/230px-Dune_2020.jpeg',
        bannerUrl:
            'https://coolhdwall.com/storage/202106/dune-movie-2021-cast-and-characters-4k-phone-wallpaper-2160x3840.jpg',
        age: '14',
        release: '2019',
        rate: '8.5',
        time: '2h 4m',
        genre: 'Action',
        castImages: [
          'https://images.mubicdn.net/images/cast_member/430406/cache-612519-1606127472/image-w856.jpg?size=800x',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDpdn3MaOCrGtrQKEZ3ujVcK5tsWTI53MW7sWqjqbEYQ&s',
          'https://images.mubicdn.net/images/cast_member/350615/cache-128294-1533458422/image-w856.jpg',
          'https://static.wikia.nocookie.net/moviepedia/images/c/c7/Oscar-Isaac.jpg/revision/latest?cb=20141102210139&path-prefix=de',
          'https://musicimage.xboxlive.com/catalog/video.contributor.6a026500-0200-11db-89ca-0019b92a3933/image?locale=fr-ch&target=circle',
          'https://i.discogs.com/-ihfU8Jdg5cULef-eagFT3ISJ-Tt_2jpqS8lzRbYa4Y/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTExODQx/NjYtMTI2NDA3MzM5/Mi5qcGVn.jpeg',
          'https://media.vanityfair.com/photos/63b70e194373b00ff0436fac/master/w_2560%2Cc_limit/1433948913',
          'https://upload.wikimedia.org/wikipedia/commons/c/cf/ChristopherWalkenFeb08.jpg',
          'https://images.mubicdn.net/images/cast_member/2244/cache-1399-1516559658/image-w856.jpg?size=800x',
          'https://br.web.img2.acsta.net/pictures/18/06/21/17/52/2749597.jpg',
        ],
        castNames: [
          'Timothée Chalamet',
          'Zendaya',
          'Rebecca Ferguson',
          'Oscar Isaac',
          'Jason Momoa',
          'Stellan Skarsgård',
          'Dave Bautista',
          'Christopher Walken',
          'Javier Bardem',
          'Josh Brolin',
        ],
        storyline: [
          "A noble family becomes embroiled in a war for control over the galaxy's most valuable asset while its heir becomes troubled by visions of a dark future."
        ],
      ),
      Video(
        id: 'ilX5hnH8XoI7',
        author: 'currentUser',
        title: 'Avatar: The Way of Water',
        trailerURL: '',
        imageUrl:
            'https://a-static.mlcdn.com.br/1500x1500/poster-cartaz-avatar-2-o-caminho-da-agua-a-pop-arte-poster/poparteskins2/15983151125/05b13cd9c00028a453c58a879eceb94e.jpeg',
        bannerUrl:
            'https://4kwallpapers.com/images/wallpapers/avatar-the-way-of-water-avatar-2-2022-movies-sam-2732x2732-8963.jpg',
        age: '13',
        release: '2022',
        rate: '8.5',
        time: '3h 12m',
        genre: 'Action',
        castImages: [
          'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Sam_Worthington_2013.jpg/640px-Sam_Worthington_2013.jpg',
          'https://br.web.img3.acsta.net/c_310_420/pictures/19/10/17/01/24/5480352.jpg',
          'https://media.fstatic.com/aQWQneY5DIRfD4unUrjZFc062N8=/210x312/smart/filters:format(webp)/media/artists/avatar/2021/10/sigourney-weaver_a72.jpg',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRiPWqu1LHAhnPYDi5XfsgZmUV8vzdNF0nXGKJLl9YOK9HP26FjlUDj4Wh55UvYWMk7R8&usqp=CAU',
          'https://media.fstatic.com/ZVrFMm62AEJFvzVQqXG_XWXttZ4=/210x312/smart/filters:format(webp)/media/artists/avatar/2022/12/stephen-lang-i_a6152.jpg',
          'https://cdn.britannica.com/98/238198-050-9A1C1028/Michelle-Yeoh-2022.jpg',
          'https://musicimage.xboxlive.com/catalog/video.contributor.e5fa6400-0200-11db-89ca-0019b92a3933/image?locale=pt-br&target=circle',
          'https://macmagazine.com.br/wp-content/uploads/2023/02/03-cliff-curtis.jpeg',
          'https://m.media-amazon.com/images/M/MV5BMTgyMGVkN2ItZWNiNS00OThiLWIwZDUtNjM2MGRmNWFkMDY3XkEyXkFqcGdeQXVyODA4NzgwOTM@._V1_.jpg',
          'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Britain_Dalton.jpg/1200px-Britain_Dalton.jpg',
          'https://images.mubicdn.net/images/cast_member/156408/cache-176237-1475631879/image-w856.jpg?size=800x',
          'https://iv1.lisimg.com/image/23969063/740full-filip-geljo.jpg',
          'https://br.web.img3.acsta.net/c_310_420/pictures/18/11/22/23/44/2914666.jpg',
        ],
        castNames: [
          'Sam Worthington',
          'Zoë Saldaña',
          'Sigourney Weaver',
          'Kate Winslet',
          'Stephen Lang',
          'Michelle Yeoh',
          'Vin Diesel',
          'Cliff Curtis',
          'Trinity Jo-Li Bliss',
          'Britain Dalton',
          'Oona Chaplin'
              'Filip Geljo',
          'Michelle Rodriguez',
        ],
        storyline: [
          "Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na'vi race to protect their home.",
        ],
      ),
      Video(
        id: 'ilX5hnH8XoI8',
        author: 'currentUser',
        title: 'Top Gun: Maverick',
        trailerURL: '',
        imageUrl:
            'https://play-lh.googleusercontent.com/oymP-vT3PYv9lSIlJQ8Mz6j10gQiCCxh65JJR0rPGQfk6zlDNVvh4kkq3YQh6g06XdDwqYit0MRaLPF22A',
        bannerUrl:
            'https://d2s94cyhu2tzlj.cloudfront.net/assets/photos/2022/top-gun-maverick-the-need-for-speed-continues/_articlePhotoFull/top-gun-maverick-ver5-xlg-2-1.jpg?mtime=20220524091657',
        age: '13',
        release: '2022',
        rate: '8.3',
        time: '2h 10m',
        genre: 'Action',
        castImages: [
          'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Tom_Cruise_avp_2014_3.jpg/220px-Tom_Cruise_avp_2014_3.jpg',
          'https://conteudo.imguol.com.br/c/entretenimento/8b/2021/05/28/miles-teller-1622234281407_v2_3x4.jpg',
          'https://img.melhoresfilmes.com.br/unsafe/480x640/https%3A%2F%2Fwww.melhoresfilmes.com.br%2Fstorage%2Fimgs%2Factors%2F6963.jpg%3Ft%3D20221025001333',
          'https://www.themoviedb.org/t/p/w500/lRbbndkwOXyvep9Y7kHiwbh9Ji5.jpg',
          'https://ntvb.tmsimg.com/assets/assets/350_v9_bc.jpg?w=270&h=360',
          'https://flxt.tmsimg.com/assets/217907_v9_bb.jpg',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHyjkXjqNKQG1ovfXw1umRx74acuMoyyuZKuEiXh-m&s',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQOFFd4dwe5GJSgpnksqhFrzwaEqaBS_PMXjqJyISf&s',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCZJ66r3U9U6hW2iNMAaOEc4cDS2Rc5AhplXdeNxA3k1Z0-Y37zpgjNy562pu9HJ9x1jE&usqp=CAU',
          'https://cinema10.com.br/upload/personalidades/personalidades_5321_Ed-Harris.jpg',
        ],
        castNames: [
          'Tom Cruise',
          'Miles Teller',
          'Val Kilmer',
          'Glen Powell',
          'Jennifer Connelly',
          'Jon Hamm',
          'Monica Barbaro',
          'Lewis Pullman',
          'Jay Ellis',
          'Ed Harris',
        ],
        storyline: [
          "After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUN's elite graduates on a mission that demands the ultimate sacrifice from those chosen to fly it.",
        ],
      ),
      Video(
        id: 'ilX5hnH8XoI9',
        author: 'currentUser',
        title: 'Ant-Man and the Wasp: Quantumania',
        trailerURL: '',
        imageUrl:
            'https://lumiere-a.akamaihd.net/v1/images/p_antmanquantumania_update_1006_122aeffe.jpeg?region=0%2C0%2C540%2C810',
        bannerUrl:
            'https://images.news18.com/ibnlive/uploads/2023/02/paul-rudd-ant-man-3-1.jpg',
        age: '13',
        release: '2022',
        rate: '6.5',
        time: '2h 4m',
        genre: 'Action',
        castImages: [
          'https://static.wikia.nocookie.net/marvelmovies/images/d/dd/Kathryn_Newton.jpg/revision/latest?cb=20230208220033',
          'https://p2.trrsf.com/image/fget/cf/940/0/images.terra.com/2023/03/07/334617210-jonathan-majors.jpg',
          'https://br.web.img2.acsta.net/c_310_420/pictures/19/04/29/20/15/4442259.jpg',
          'https://images.mubicdn.net/images/cast_member/4954/cache-3343-1600874914/image-w856.jpg',
          'https://static.wikia.nocookie.net/marvelcinematicuniverse/images/5/57/Tony_McCarthy.jpg/revision/latest?cb=20201104210004',
          'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Bill_Murray-8882.jpg/1200px-Bill_Murray-8882.jpg',
          'https://www.themoviedb.org/t/p/w500/8eTtJ7XVXY0BnEeUaSiTAraTIXd.jpg',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJReVVaedmPMZYQgfkGcxtsllnZ2LCtodv6J96UfVNVUNHBH6GKNe2CMV9Vx6ZU3zeSFg&usqp=CAU',
          'https://static.wikia.nocookie.net/dublagem/images/6/68/Hannah-john-kamen_1.jpg/revision/latest?cb=20211208180453&path-prefix=pt-br',
          'https://br.web.img3.acsta.net/pictures/19/10/16/03/30/0181749.jpg',
          'https://musicimage.xboxlive.com/catalog/video.contributor.6bf96400-0200-11db-89ca-0019b92a3933/image?locale=pt-br&target=circle',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS73Zdw7Bn-QUgQkfrW5HF5xAhEOukRqHH4t3h1_zUHqOddjkbgbe2MEZsNesVDz99MTgY&usqp=CAU',
        ],
        castNames: [
          'Kathryn Newton',
          'Jonathan Majors',
          'Evangeline Lilly',
          'Michelle Pfeiffer',
          'Tony McCarthy',
          'Bill Murray',
          'Paul Rudd',
          "Katy M. O'Brian",
          'Hannah John-Kamen',
          'William Jackson Harper',
          'Corey Stoll',
          'Michael Peña',
        ],
        storyline: [
          "Scott Lang and Hope Van Dyne, along with Hank Pym and Janet Van Dyne, explore the Quantum Realm, where they interact with strange creatures and embark on an adventure that goes beyond the limits of what they thought was possible.",
        ],
      ),
      Video(
        id: 'ilX5hnH8XoI10',
        author: 'currentUser',
        title: 'M3GAN',
        trailerURL: '',
        imageUrl:
            'https://images.fandango.com/ImageRenderer/820/0/redesign/static/img/default_poster.png/0/images/masterrepository/fandango/229737/382738id1c_M3GAN_BusShelter_48x70_RGB.jpg',
        bannerUrl:
            'https://pittnews.com/wp-content/uploads/2023/01/C_MeganMovie_Via.png',
        age: '13',
        release: '2022',
        rate: '6.4',
        time: '1h 42m',
        genre: 'Horror',
        castImages: [],
        castNames: [
          'Brad Pitt',
          'Tommy Lee Jones',
          'Donald Sutherland',
          'Ruth Negga',
          'Liv Tyler',
          'Kayla Adams',
          'Natasha Lyonne',
          'Kimberly Elise',
          'Greg Bryk',
        ],
        storyline: [
          "A robotics engineer at a toy company builds a life-like doll that begins to take on a life of its own.",
        ],
      ),
      Video(
        id: 'ilX5hnH8XoI11',
        author: 'currentUser',
        title: 'Bullet Train',
        trailerURL: '',
        imageUrl:
            'https://upload.wikimedia.org/wikipedia/pt/0/08/Bullet_train_filme.jpg',
        bannerUrl:
            'https://d1fmx1rbmqrxrr.cloudfront.net/cnet/optim/i/edit/2022/07/bullet%20train%20critique%20big__w770.jpg',
        age: 'R',
        release: '2022',
        rate: '7.3',
        time: '2h 7m',
        genre: 'Comedy',
        castImages: [],
        castNames: [
          'Brad Pitt',
          'Tommy Lee Jones',
          'Donald Sutherland',
          'Ruth Negga',
          'Liv Tyler',
          'Kayla Adams',
          'Natasha Lyonne',
          'Kimberly Elise',
          'Greg Bryk',
        ],
        storyline: [
          "Five assassins aboard a swiftly-moving bullet train find out that their missions have something in common.",
        ],
      ),
    ];

    notifyListeners();
  }
}
